# Generated by Django 4.2.11 on 2024-03-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_studentsubjectcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='bdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
