# Generated by Django 4.2.11 on 2024-03-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_studentdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubjectcourse',
            name='section',
        ),
    ]
