# Generated by Django 4.2.11 on 2024-03-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_subjectmeeting_platform_alter_subjectmeeting_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmeeting',
            name='teacher',
        ),
    ]
